version: '3.5'
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: gns-api
    ports:
    - 27017:27017

  mongo-seed:
    image: pkosiec/mongo-seeding:3.2.0
    hostname: mongo-seed
    depends_on:
    - mongodb
    volumes:
    - ${PWD}/data:/mongo-seed/data
    working_dir: /mongo-seed/data
    environment:
      DB_URI: mongodb://user:pass@mongodb:27017/gns-api?authMechanism=SCRAM-SHA-1&authSource=admin

  api:
    build: .
    depends_on: 
    - mongodb
    restart: on-failure
